env:
 - GHCVER=7.6.1
 - GHCVER=7.6.2
 - GHCVER=7.6.3
 - GHCVER=7.8.1
 - GHCVER=7.8.2
 - GHCVER=head

matrix:
  allow_failures:
    - env: GHCVER=head

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-1.18 ghc-$GHCVER
 - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/1.18/bin:$PATH

install:
 - cabal update
 - cabal sandbox init
 - cabal install hpc-coveralls --bindir=$HOME/.cabal/bin/
 - cabal sandbox delete
 - cabal install happy
 - cabal install --only-dependencies --enable-tests --constraint 'process-conduit < 1.2.0' --constraint 'attoparsec-conduit < 1.1.0'

script:
 - cabal configure --enable-tests -v2  # -v2 provides useful information for debugging
 - cabal build   # this builds all libraries and executables (including tests/benchmarks)
 - cabal test
 - cabal check
 - cabal sdist   # tests that a source-distribution can be generated

 - export SRC_TGZ=$(cabal-1.18 info . | awk '{print $2 ".tar.gz";exit}') ;
   cd dist/;
   if [ -f "$SRC_TGZ" ]; then
      cabal install "$SRC_TGZ";
   else
      echo "expected '$SRC_TGZ' not found";
      exit 1;
   fi

# We con not get test coverage data using `cabal test`
# so execute binary of test suites directly
after_script:
 - cd ..
 - cabal clean
 - cabal configure --enable-tests -v2 --enable-library-coverage # -v2 provides useful information for debugging
 - cabal build
 - ./dist/build/test-prefork/test-prefork
 - ./dist/build/test-prefork-server/test-prefork-server
 - mkdir -p dist/hpc/tix/test-prefork
 - mkdir -p dist/hpc/tix/test-prefork-server
 - mv test-prefork.tix dist/hpc/tix/test-prefork/
 - mv test-prefork-server.tix dist/hpc/tix/test-prefork-server/
 - hpc-coveralls --exclude-dir=test test-prefork test-prefork-server
